name: CIworkflow
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker-compose -f ./docker-compose.yml up --build -d
      - name: Push to dockerHub
        run: docker-compose -f ./docker-compose.yml push

          
      
