name: appTest
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - run: npm install -g yarn
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
      - run: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      - run: source ~/.bashrc   
      - run: nvm install 16
      - run: nvm use 16
      - name: Download dependencies
        working-directory: ./api
        run: |
          yarn && yarn seed
          npm install --save-dev jest supertest
      - name: run test
        working-directory: ./api
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
